FROM public.ecr.aws/lambda/python:3.9

RUN yum groupinstall -y "Development Tools" && \
    yum install -y \
    curl \
    && rm -rf /var/cache/yum

RUN curl -O ftp://ftp.freetds.org/pub/freetds/stable/freetds-1.2.tar.gz && \
    tar -xvzf freetds-1.2.tar.gz && \
    cd freetds-1.2 && \
    ./configure && \
    make && \
    make install && \
    cd .. && \
    rm -rf freetds-1.2 freetds-1.2.tar.gz

RUN yum clean all

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY pipeline/extract.py .
COPY pipeline/transform.py .
COPY pipeline/load.py .
COPY pipeline/etl.py .


CMD ["etl.lambda_handler"]



