FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    freetds-bin \
    freetds-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY extract_from_database.py .

CMD ["python3.9", "extract_from_database.py"]